name: wlist_ui
description: "The ui part of wlist."
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ^3.4.3


dependencies:
  # flutter
  flutter:
    sdk: flutter
  ## basic
  ### i18n
  flutter_localizations:
    sdk: flutter
  ### window
  window_manager: ^0.4.0
  ### toast
  toastification: ^2.1.0
  ## storage
  shared_preferences: ^2.3.1
  path_provider: ^2.1.4
  #  device_info_plus: ^10.1.0
  # rust
  rust_lib_wlist_ui:
    path: rust_builder
  flutter_rust_bridge: 2.3.0

dev_dependencies:
  # flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # rust
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
